name       : stone-soup
version    : 0.30.1
release    : 15
source     :
    - https://github.com/crawl/crawl/releases/download/0.30.1/stone_soup-0.30.1-nodeps.tar.xz : 906d376ef8001fbf9f7a05245030f64f9300c6ce3855d2f8dc81cd8d48ef0a46
license    :
    - BSD-2-Clause
    - CC0-1.0
    - GPL-2.0
homepage   : https://crawl.develz.org
component  : games.rpg
summary    : Dungeon Crawl Stone Soup - Roguelike RPG
description: |
    A roguelike adventure through dungeons filled with dangerous monsters in a quest to find the mystifyingly fabulous Orb of Zot.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libpng)
    - pkgconfig(lua-5.1)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(sqlite3)
    - dejavu-fonts-ttf
rundeps    :
    - dejavu-fonts-ttf
    - pyyaml
setup      : |
    %patch -p1 < $pkgfiles/0001-Ensure-we-use-correct-lua-5.1-header-location.patch
build      : |
    cd source
    sed -i "s/bin_prefix    := games/bin_prefix    := bin/" Makefile
    %make TILES=y SOUND=y
    %make_install TILES=y SOUND=y prefix=/usr
    mv $installdir/usr/bin/crawl $installdir/usr/bin/crawl-tiles
    %make
install    : |
    cd source
    %make_install prefix=/usr
    install -D -m 00644 $pkgfiles/stone-soup.desktop $installdir/usr/share/applications/stone-soup.desktop
    install -D -m 00644 $pkgfiles/stone-soup-tiles.desktop $installdir/usr/share/applications/stone-soup-tiles.desktop
