name       : stone-soup
version    : 0.19.1
release    : 3
source     :
    - http://crawl.develz.org/release/stone_soup-0.19.1-nodeps.tar.xz : ad9a54e0fde78f5fd08f074f7a024dd8d180c7b8c7cd65fa4bd1dac51f340b2c
license    :
    - BSD-2-Clause
    - CC0-1.0
    - GPL-2.0
component  : games.rpg
summary    : Dungeon Crawl Stone Soup - Roguelike RPG
description: |
    A roguelike adventure through dungeons filled with dangerous monsters in a quest to find the mystifyingly fabulous Orb of Zot.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libpng)
    - pkgconfig(lua-5.1)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(sqlite3)
    - dejavu-fonts-ttf
rundeps    :
    - dejavu-fonts-ttf
build      : |
    cd source
    sed -i "s/bin_prefix    := games/bin_prefix    := bin/" Makefile
    %make TILES=y SOUND=y
    %make_install TILES=y SOUND=y prefix=/usr
    mv $installdir/usr/bin/crawl $installdir/usr/bin/crawl-tiles
    %make
    %make_install prefix=/usr
install    : |-
    install -D -m 00644 $pkgfiles/stone-soup.desktop $installdir/usr/share/applications/stone-soup.desktop
    install -D -m 00644 $pkgfiles/stone-soup-tiles.desktop $installdir/usr/share/applications/stone-soup-tiles.desktop
