name       : stone-soup
version    : 0.21.0
release    : 8
source     :
    - https://crawl.develz.org/release/0.21/stone_soup-0.21.0.tar.xz : fc8fb430c0fd485e9f91e396249a74c63d3bdb80d0104b3384bd697dd1802013
license    :
    - BSD-2-Clause
    - CC0-1.0
    - GPL-2.0
component  : games.rpg
summary    : Dungeon Crawl Stone Soup - Roguelike RPG
description: |
    A roguelike adventure through dungeons filled with dangerous monsters in a quest to find the mystifyingly fabulous Orb of Zot.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libpng)
    - pkgconfig(lua-5.1)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(sqlite3)
    - dejavu-fonts-ttf
rundeps    :
    - dejavu-fonts-ttf
setup      : |
    %patch -p1 < $pkgfiles/0001-Ensure-we-use-correct-lua-5.1-header-location.patch
build      : |
    cd source
    sed -i "s/bin_prefix    := games/bin_prefix    := bin/" Makefile
    %make TILES=y SOUND=y
    %make_install TILES=y SOUND=y prefix=/usr
    mv $installdir/usr/bin/crawl $installdir/usr/bin/crawl-tiles
    %make
install    : |
    cd source
    %make_install prefix=/usr
    install -D -m 00644 $pkgfiles/stone-soup.desktop $installdir/usr/share/applications/stone-soup.desktop
    install -D -m 00644 $pkgfiles/stone-soup-tiles.desktop $installdir/usr/share/applications/stone-soup-tiles.desktop
